apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spring-backend-postgres-password
  namespace: this-dev-1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: dd-this-2-dev/this-dev-1/POSTGRES_PASSWORD
