apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spring-frontend-github-client-secret
  namespace: this-dev-1
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: deepagent-aws
    kind: ClusterSecretStore
  target:
    name: app-env
    creationPolicy: Merge
  data:
    - secretKey: GITHUB_CLIENT_SECRET
      remoteRef:
        key: dd-this-2-dev/this-dev-1/GITHUB_CLIENT_SECRET
